In [47]:
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
warnings.filterwarnings("ignore")

In [48]:
df = pd.read_csv(r"D:\Genai_Projects\ai_ecom_agent\Data\sentiment.csv")

In [49]:
df.head()

text Sentiment
0  super! great cooler excellent air flow and for...  positive
1      awesome best budget 2 fit cooler nice cooling  positive
2  fair the quality is good but the power of air ...  positive
3  useless product very bad product its a only a fan  negative
4                                 fair ok ok product   neutral

In [50]:
df.tail()

text Sentiment
205047                             must buy! good product  positive
205048                                        super! nice  positive
205049                   nice very nice and fast delivery  positive
205050                          just wow! awesome product  positive
205051  value-for-money very good but mixing bowl not ...   neutral

In [51]:
df = df.drop(columns=["product_name","product_price","Rate"],axis=1)

KeyError: "['product_name', 'product_price', 'Rate'] not found in axis"

In [ ]:
df

Review  ... Sentiment
0                super!  ...  positive
1               awesome  ...  positive
2                  fair  ...  positive
3       useless product  ...  negative
4                  fair  ...   neutral
...                 ...  ...       ...
205047        must buy!  ...  positive
205048           super!  ...  positive
205049             nice  ...  positive
205050        just wow!  ...  positive
205051  value-for-money  ...   neutral

[205052 rows x 3 columns]

In [ ]:
df["text"] = df["Review"].astype(str) + " " + df["Summary"].astype(str)

In [ ]:
df.drop(columns=["Review","Summary"],axis=1,inplace=True)

In [ ]:
df

Sentiment                                               text
0       positive  super! great cooler excellent air flow and for...
1       positive      awesome best budget 2 fit cooler nice cooling
2       positive  fair the quality is good but the power of air ...
3       negative  useless product very bad product its a only a fan
4        neutral                                 fair ok ok product
...          ...                                                ...
205047  positive                             must buy! good product
205048  positive                                        super! nice
205049  positive                   nice very nice and fast delivery
205050  positive                          just wow! awesome product
205051   neutral  value-for-money very good but mixing bowl not ...

[205052 rows x 2 columns]

In [ ]:
cols = ["text","Sentiment"]
df = df[cols]

In [ ]:
df.to_csv(r"D:\Genai_Projects\ai_ecom_agent\Data\sentiment.csv", index=False)

In [ ]:
df

text Sentiment
0       super! great cooler excellent air flow and for...  positive
1           awesome best budget 2 fit cooler nice cooling  positive
2       fair the quality is good but the power of air ...  positive
3       useless product very bad product its a only a fan  negative
4                                      fair ok ok product   neutral
...                                                   ...       ...
205047                             must buy! good product  positive
205048                                        super! nice  positive
205049                   nice very nice and fast delivery  positive
205050                          just wow! awesome product  positive
205051  value-for-money very good but mixing bowl not ...   neutral

[205052 rows x 2 columns]

In [ ]:
X = df["text"]
y = df["Sentiment"]

In [ ]:
import re

def clean_data(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', ' ', text)   
    text = re.sub(r'\s+', ' ', text).strip()
    return text

X = X.apply(clean_data)

In [ ]:
X.head()

0    super! great cooler excellent air flow and for...
1        awesome best budget 2 fit cooler nice cooling
2    fair the quality is good but the power of air ...
3    useless product very bad product its a only a fan
4                                   fair ok ok product
Name: text, dtype: object

In [ ]:
X

0         super great cooler excellent air flow and for ...
1               awesome best budget fit cooler nice cooling
2         fair the quality is good but the power of air ...
3         useless product very bad product its a only a fan
4                                        fair ok ok product
                                ...                        
205047                                must buy good product
205048                                           super nice
205049                     nice very nice and fast delivery
205050                             just wow awesome product
205051    value for money very good but mixing bowl not ...
Name: text, Length: 205052, dtype: object

In [ ]:

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')        # for tokenization
nltk.download('punkt_tab')    # fixes "punkt_tab" error in newer NLTK versions
nltk.download('stopwords')    # for removing stopwords
nltk.download('wordnet')      # for lemmatization
nltk.download('omw-1.4')      # for lemmatizer (WordNet data)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sahil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\sahil\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sahil\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sahil\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\sahil\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def processing(text):
    text = word_tokenize(text)                                
    text = [word for word in text if word not in stop_words]  
    text = [lemmatizer.lemmatize(word) for word in text]      
    return text

X = X.apply(processing)

    

In [ ]:
X

0         [super, great, cooler, excellent, air, flow, p...
1         [awesome, best, budget, fit, cooler, nice, coo...
2                 [fair, quality, good, power, air, decent]
3                     [useless, product, bad, product, fan]
4                                   [fair, ok, ok, product]
                                ...                        
205047                           [must, buy, good, product]
205048                                        [super, nice]
205049                         [nice, nice, fast, delivery]
205050                              [wow, awesome, product]
205051    [value, money, good, mixing, bowl, included, o...
Name: text, Length: 205052, dtype: object

In [ ]:
X = X.apply(lambda tokens: " ".join(tokens))

In [ ]:
X

0         super great cooler excellent air flow price am...
1               awesome best budget fit cooler nice cooling
2                        fair quality good power air decent
3                           useless product bad product fan
4                                        fair ok ok product
                                ...                        
205047                                must buy good product
205048                                           super nice
205049                              nice nice fast delivery
205050                                  wow awesome product
205051    value money good mixing bowl included one disa...
Name: text, Length: 205052, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.25, random_state=42)
vectorizer = TfidfVectorizer(max_features=5000)
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
mnb = MultinomialNB()
mnb.fit(X_train,y_train)
y_pred = mnb.predict(X_test)
acc_score = accuracy_score(y_pred=y_pred,y_true=y_test)
matrix = confusion_matrix(y_pred=y_pred,y_true=y_test)
report = classification_report(y_pred=y_pred,y_true=y_test)
print("accuracy" , acc_score)
print(matrix)
print(report)

accuracy 0.9205274759573181
[[ 5802    76  1043]
 [  634   517  1400]
 [  755   166 40870]]
              precision    recall  f1-score   support

    negative       0.81      0.84      0.82      6921
     neutral       0.68      0.20      0.31      2551
    positive       0.94      0.98      0.96     41791

    accuracy                           0.92     51263
   macro avg       0.81      0.67      0.70     51263
weighted avg       0.91      0.92      0.91     51263



In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.25, random_state=42)
vectorizer = TfidfVectorizer(max_features=5000,ngram_range=(1,2))
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(class_weight="balanced")
logistic.fit(X_train,y_train)
y_pred = logistic.predict(X_test)
acc_score = accuracy_score(y_pred=y_pred,y_true=y_test)
matrix = confusion_matrix(y_pred=y_pred,y_true=y_test)
report = classification_report(y_pred=y_pred,y_true=y_test)
print("accuracy" , acc_score)
print(matrix)
print(report)

accuracy 0.8961824317734038
[[ 6121   686   114]
 [  369  1899   283]
 [  694  3176 37921]]
              precision    recall  f1-score   support

    negative       0.85      0.88      0.87      6921
     neutral       0.33      0.74      0.46      2551
    positive       0.99      0.91      0.95     41791

    accuracy                           0.90     51263
   macro avg       0.72      0.85      0.76     51263
weighted avg       0.94      0.90      0.91     51263



In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle
import pandas as pd
import numpy as np

nltk.download('punkt')        # for tokenization
nltk.download('punkt_tab')    # fixes "punkt_tab" error in newer NLTK versions
nltk.download('stopwords')    # for removing stopwords
nltk.download('wordnet')      # for lemmatization
nltk.download('omw-1.4') 

class NltkPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.stop_words = set(stopwords.words("english"))
        self.lemmatizer = WordNetLemmatizer()

    def clean_data(self, text: str) -> str:
        text = "" if text is None or (isinstance(text, float) and np.isnan(text)) else str(text)
        text = text.lower()
        # keep letters + spaces, drop everything else
        text = re.sub(r"[^a-z\s]", " ", text)
        text = re.sub(r"\s+", " ", text).strip()
        return text

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        # X can be list/Series/ndarray; return list[str]
        if isinstance(X, (pd.Series, pd.DataFrame)):
            X = X.squeeze()
        processed = []
        for txt in X:
            txt = self.clean_data(txt)
            tokens = word_tokenize(txt)
            tokens = [t for t in tokens if t not in self.stop_words]
            tokens = [self.lemmatizer.lemmatize(t) for t in tokens]
            processed.append(" ".join(tokens))
        return processed

# -------- data --------
df = pd.read_csv(r"D:\Genai_Projects\ai_ecom_agent\Data\sentiment.csv")
X = df["text"]
y = df["Sentiment"]

# -------- split --------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

# -------- pipeline --------
pipe = Pipeline([
    ("preprocess", NltkPreprocessor()),
    ("tfidf", TfidfVectorizer(max_features=5000, ngram_range=(1,2))),
    ("clf", LogisticRegression(class_weight="balanced", max_iter=2000, solver="saga"))
])

# -------- train --------
pipe.fit(X_train, y_train)

# -------- evaluate --------
y_pred = pipe.predict(X_test)
print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))

# -------- save --------
with open(r"D:\Genai_Projects\ai_ecom_agent\models\sentiment_pipeline.pkl", "wb") as f:
    pickle.dump(pipe, f)

print("🎯 Model pipeline saved successfully!")


AttributeError: partially initialized module 'nltk' has no attribute 'data' (most likely due to a circular import)